"""create paper trading tables

Revision ID: 387817b15e45
Revises: f581188fd161
Create Date: 2026-08-27 04:08:04.598863

Also seeds the one `paper_accounts` row (Step 8: "initial paper account
equity should come from RISK_STARTING_EQUITY") from
`app.core.config.Settings.risk_starting_equity` at the moment this
migration runs, so `PaperTradingService`/`PortfolioStateProvider` always
have exactly one account row to find on a fresh database — mirrors the
same seed-on-migrate pattern the Phase 6 `risk_policies` migration
already used for its one active policy row.
"""
import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '387817b15e45'
down_revision: Union[str, None] = 'f581188fd161'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paper_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('starting_equity', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('cash', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('peak_equity', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('cash >= 0', name='ck_paper_accounts_cash_non_negative'),
    sa.CheckConstraint('peak_equity > 0', name='ck_paper_accounts_peak_equity'),
    sa.CheckConstraint('starting_equity > 0', name='ck_paper_accounts_starting_equity'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paper_positions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('avg_entry_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=20, scale=8), server_default=sa.text('0'), nullable=False),
    sa.Column('status', sa.String(length=10), server_default='OPEN', nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('OPEN', 'CLOSED')", name='ck_paper_positions_status'),
    sa.CheckConstraint('quantity >= 0', name='ck_paper_positions_quantity_non_negative'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_paper_positions_open_asset', 'paper_positions', ['asset_id'], unique=True, postgresql_where=sa.text("status = 'OPEN'"))
    op.create_index('ix_paper_positions_status', 'paper_positions', ['status'], unique=False)
    op.create_table('paper_orders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('signal_id', sa.UUID(), nullable=True),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('order_type', sa.String(length=10), server_default='MARKET', nullable=False),
    sa.Column('quantity', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('requested_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('status', sa.String(length=10), server_default='PENDING', nullable=False),
    sa.Column('filled_quantity', sa.Numeric(precision=28, scale=10), server_default=sa.text('0'), nullable=False),
    sa.Column('average_fill_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("order_type = 'MARKET'", name='ck_paper_orders_order_type'),
    sa.CheckConstraint("side IN ('BUY', 'SELL')", name='ck_paper_orders_side'),
    sa.CheckConstraint("status IN ('PENDING', 'FILLED', 'REJECTED', 'CANCELLED')", name='ck_paper_orders_status'),
    sa.CheckConstraint('filled_quantity >= 0 AND filled_quantity <= quantity', name='ck_paper_orders_filled_quantity_bounds'),
    sa.CheckConstraint('quantity > 0', name='ck_paper_orders_quantity_positive'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('signal_id')
    )
    op.create_index('ix_paper_orders_asset_id', 'paper_orders', ['asset_id'], unique=False)
    op.create_index('ix_paper_orders_created_at', 'paper_orders', ['created_at'], unique=False)
    op.create_index('ix_paper_orders_status', 'paper_orders', ['status'], unique=False)
    op.create_table('paper_fills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('fill_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('fee', sa.Numeric(precision=20, scale=8), server_default=sa.text('0'), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('fee >= 0', name='ck_paper_fills_fee_non_negative'),
    sa.CheckConstraint('fill_price > 0', name='ck_paper_fills_price_positive'),
    sa.CheckConstraint('quantity > 0', name='ck_paper_fills_quantity_positive'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['paper_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_paper_fills_asset_id', 'paper_fills', ['asset_id'], unique=False)
    op.create_index('ix_paper_fills_order_id', 'paper_fills', ['order_id'], unique=False)
    op.create_index('ix_paper_fills_timestamp', 'paper_fills', ['timestamp'], unique=False)
    # ### end Alembic commands ###

    from app.core.config import get_settings

    starting_equity = get_settings().risk_starting_equity
    paper_accounts = sa.table(
        'paper_accounts',
        sa.column('id', sa.UUID()),
        sa.column('starting_equity', sa.Numeric()),
        sa.column('cash', sa.Numeric()),
        sa.column('peak_equity', sa.Numeric()),
    )
    op.bulk_insert(
        paper_accounts,
        [
            {
                'id': uuid.uuid4(),
                'starting_equity': starting_equity,
                'cash': starting_equity,
                'peak_equity': starting_equity,
            }
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_paper_fills_timestamp', table_name='paper_fills')
    op.drop_index('ix_paper_fills_order_id', table_name='paper_fills')
    op.drop_index('ix_paper_fills_asset_id', table_name='paper_fills')
    op.drop_table('paper_fills')
    op.drop_index('ix_paper_orders_status', table_name='paper_orders')
    op.drop_index('ix_paper_orders_created_at', table_name='paper_orders')
    op.drop_index('ix_paper_orders_asset_id', table_name='paper_orders')
    op.drop_table('paper_orders')
    op.drop_index('ix_paper_positions_status', table_name='paper_positions')
    op.drop_index('ix_paper_positions_open_asset', table_name='paper_positions', postgresql_where=sa.text("status = 'OPEN'"))
    op.drop_table('paper_positions')
    op.drop_table('paper_accounts')
    # ### end Alembic commands ###
