"""create assets and market_data tables

Revision ID: 973483b300ce
Revises: 
Create Date: 2026-08-26 19:06:43.858336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '973483b300ce'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('asset_type', sa.String(length=20), nullable=False),
    sa.Column('exchange', sa.String(length=50), nullable=True),
    sa.Column('currency', sa.String(length=10), server_default='USD', nullable=False),
    sa.Column('active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("asset_type IN ('equity', 'etf', 'crypto', 'forex')", name='ck_assets_asset_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'asset_type', name='uq_assets_symbol_asset_type')
    )
    op.create_index(op.f('ix_assets_symbol'), 'assets', ['symbol'], unique=False)
    op.create_table('market_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('high', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('low', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('close', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('volume', sa.Numeric(precision=28, scale=10), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('interval', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("interval IN ('1m', '5m', '15m', '1h', '1d')", name='ck_market_data_interval'),
    sa.CheckConstraint('high >= close', name='ck_market_data_high_gte_close'),
    sa.CheckConstraint('high >= low', name='ck_market_data_high_gte_low'),
    sa.CheckConstraint('high >= open', name='ck_market_data_high_gte_open'),
    sa.CheckConstraint('low <= close', name='ck_market_data_low_lte_close'),
    sa.CheckConstraint('low <= open', name='ck_market_data_low_lte_open'),
    sa.CheckConstraint('open > 0 AND high > 0 AND low > 0 AND close > 0', name='ck_market_data_prices_positive'),
    sa.CheckConstraint('volume >= 0', name='ck_market_data_volume_non_negative'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'interval', 'timestamp', 'source', name='uq_market_data_asset_interval_ts_source')
    )
    op.create_index(op.f('ix_market_data_asset_id'), 'market_data', ['asset_id'], unique=False)
    op.create_index('ix_market_data_asset_timestamp', 'market_data', ['asset_id', 'timestamp'], unique=False)
    op.create_index(op.f('ix_market_data_timestamp'), 'market_data', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_market_data_timestamp'), table_name='market_data')
    op.drop_index('ix_market_data_asset_timestamp', table_name='market_data')
    op.drop_index(op.f('ix_market_data_asset_id'), table_name='market_data')
    op.drop_table('market_data')
    op.drop_index(op.f('ix_assets_symbol'), table_name='assets')
    op.drop_table('assets')
    # ### end Alembic commands ###
