"""create signals table

Revision ID: e0a159731764
Revises: b945f6932f93
Create Date: 2026-08-26 23:40:37.688680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e0a159731764'
down_revision: Union[str, None] = 'b945f6932f93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('interval', sa.String(length=10), nullable=False),
    sa.Column('signal', sa.String(length=10), nullable=False),
    sa.Column('strategy_id', sa.String(length=50), nullable=False),
    sa.Column('strategy_version', sa.String(length=20), nullable=False),
    sa.Column('strength', sa.String(length=10), nullable=True),
    sa.Column('market_regime', sa.String(length=20), nullable=False),
    sa.Column('reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('supporting_features', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('invalidating_conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='CANDIDATE', nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("signal IN ('BUY', 'SELL', 'HOLD')", name='ck_signals_signal'),
    sa.CheckConstraint("status IN ('CANDIDATE', 'RISK_APPROVED', 'RISK_REJECTED', 'EXPIRED', 'SUPERSEDED')", name='ck_signals_status'),
    sa.CheckConstraint("strength IS NULL OR strength IN ('WEAK', 'MODERATE', 'STRONG')", name='ck_signals_strength'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_signals_asset_id'), 'signals', ['asset_id'], unique=False)
    op.create_index('ix_signals_created_at', 'signals', ['created_at'], unique=False)
    op.create_index('ix_signals_lookup', 'signals', ['asset_id', 'interval', 'strategy_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_signals_lookup', table_name='signals')
    op.drop_index('ix_signals_created_at', table_name='signals')
    op.drop_index(op.f('ix_signals_asset_id'), table_name='signals')
    op.drop_table('signals')
    # ### end Alembic commands ###
