"""create risk_policies and risk_evaluations tables

Revision ID: f581188fd161
Revises: e0a159731764
Create Date: 2026-08-27 03:01:10.866443

Also seeds the one initial active `RiskPolicy` row (Step 4: "there
should be a clear concept of the currently active policy") from the
authoritative defaults in app/services/risk_engine/defaults.py, so
`RiskService.get_active_policy()` always has exactly one row to find —
a fresh database is never in a state where risk evaluation has no
policy to evaluate against.
"""
import uuid
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f581188fd161'
down_revision: Union[str, None] = 'e0a159731764'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_policies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('max_position_size_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('max_portfolio_exposure_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('max_daily_loss_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('max_drawdown_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('stop_loss_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('take_profit_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('risk_per_trade_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('max_concurrent_positions', sa.Integer(), nullable=False),
    sa.Column('cooldown_after_loss_minutes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('cooldown_after_loss_minutes >= 0 AND cooldown_after_loss_minutes <= 10080', name='ck_risk_policies_cooldown_after_loss_minutes'),
    sa.CheckConstraint('max_concurrent_positions >= 1 AND max_concurrent_positions <= 1000', name='ck_risk_policies_max_concurrent_positions'),
    sa.CheckConstraint('max_daily_loss_pct > 0 AND max_daily_loss_pct <= 100', name='ck_risk_policies_max_daily_loss_pct'),
    sa.CheckConstraint('max_drawdown_pct > 0 AND max_drawdown_pct <= 100', name='ck_risk_policies_max_drawdown_pct'),
    sa.CheckConstraint('max_portfolio_exposure_pct > 0 AND max_portfolio_exposure_pct <= 100', name='ck_risk_policies_max_portfolio_exposure_pct'),
    sa.CheckConstraint('max_position_size_pct > 0 AND max_position_size_pct <= 100', name='ck_risk_policies_max_position_size_pct'),
    sa.CheckConstraint('risk_per_trade_pct > 0 AND risk_per_trade_pct <= 100', name='ck_risk_policies_risk_per_trade_pct'),
    sa.CheckConstraint('stop_loss_pct > 0 AND stop_loss_pct < 100', name='ck_risk_policies_stop_loss_pct'),
    sa.CheckConstraint('take_profit_pct > 0 AND take_profit_pct <= 1000', name='ck_risk_policies_take_profit_pct'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uq_risk_policies_name_version')
    )
    op.create_index('ix_risk_policies_single_active', 'risk_policies', ['is_active'], unique=True, postgresql_where=sa.text('is_active'))
    op.create_table('risk_evaluations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('signal_id', sa.UUID(), nullable=False),
    sa.Column('policy_id', sa.UUID(), nullable=False),
    sa.Column('policy_version', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(length=10), nullable=False),
    sa.Column('reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('checks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('calculated_position_size', sa.Numeric(precision=28, scale=10), nullable=True),
    sa.Column('entry_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('stop_loss_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('take_profit_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('position_value', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('portfolio_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("decision IN ('APPROVED', 'REJECTED')", name='ck_risk_evaluations_decision'),
    sa.ForeignKeyConstraint(['policy_id'], ['risk_policies.id'], ),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_risk_evaluations_created_at', 'risk_evaluations', ['created_at'], unique=False)
    op.create_index('ix_risk_evaluations_decision', 'risk_evaluations', ['decision'], unique=False)
    op.create_index('ix_risk_evaluations_signal_id', 'risk_evaluations', ['signal_id'], unique=False)
    # ### end Alembic commands ###

    from app.services.risk_engine import defaults as risk_defaults

    risk_policies = sa.table(
        'risk_policies',
        sa.column('id', sa.UUID()),
        sa.column('name', sa.String()),
        sa.column('version', sa.Integer()),
        sa.column('enabled', sa.Boolean()),
        sa.column('is_active', sa.Boolean()),
        sa.column('max_position_size_pct', sa.Numeric()),
        sa.column('max_portfolio_exposure_pct', sa.Numeric()),
        sa.column('max_daily_loss_pct', sa.Numeric()),
        sa.column('max_drawdown_pct', sa.Numeric()),
        sa.column('stop_loss_pct', sa.Numeric()),
        sa.column('take_profit_pct', sa.Numeric()),
        sa.column('risk_per_trade_pct', sa.Numeric()),
        sa.column('max_concurrent_positions', sa.Integer()),
        sa.column('cooldown_after_loss_minutes', sa.Integer()),
    )
    op.bulk_insert(
        risk_policies,
        [
            {
                'id': uuid.uuid4(),
                'name': risk_defaults.DEFAULT_POLICY_NAME,
                'version': 1,
                'enabled': True,
                'is_active': True,
                'max_position_size_pct': risk_defaults.DEFAULT_MAX_POSITION_SIZE_PCT,
                'max_portfolio_exposure_pct': risk_defaults.DEFAULT_MAX_PORTFOLIO_EXPOSURE_PCT,
                'max_daily_loss_pct': risk_defaults.DEFAULT_MAX_DAILY_LOSS_PCT,
                'max_drawdown_pct': risk_defaults.DEFAULT_MAX_DRAWDOWN_PCT,
                'stop_loss_pct': risk_defaults.DEFAULT_STOP_LOSS_PCT,
                'take_profit_pct': risk_defaults.DEFAULT_TAKE_PROFIT_PCT,
                'risk_per_trade_pct': risk_defaults.DEFAULT_RISK_PER_TRADE_PCT,
                'max_concurrent_positions': risk_defaults.DEFAULT_MAX_CONCURRENT_POSITIONS,
                'cooldown_after_loss_minutes': risk_defaults.DEFAULT_COOLDOWN_AFTER_LOSS_MINUTES,
            }
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_risk_evaluations_signal_id', table_name='risk_evaluations')
    op.drop_index('ix_risk_evaluations_decision', table_name='risk_evaluations')
    op.drop_index('ix_risk_evaluations_created_at', table_name='risk_evaluations')
    op.drop_table('risk_evaluations')
    op.drop_index('ix_risk_policies_single_active', table_name='risk_policies', postgresql_where=sa.text('is_active'))
    op.drop_table('risk_policies')
    # ### end Alembic commands ###
