"""create ai_analyses table

Revision ID: f63d117ee0c5
Revises: 387817b15e45
Create Date: 2026-08-27 10:13:12.961273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f63d117ee0c5'
down_revision: Union[str, None] = '387817b15e45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('signal_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('interval', sa.String(length=10), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('prompt_version', sa.String(length=20), nullable=False),
    sa.Column('market_summary', sa.Text(), nullable=False),
    sa.Column('thesis', sa.Text(), nullable=False),
    sa.Column('supporting_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('contradicting_evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('risks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('invalidating_conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('suggested_action', sa.String(length=10), nullable=False),
    sa.Column('action_rationale', sa.Text(), nullable=False),
    sa.Column('uncertainty', sa.String(length=10), nullable=False),
    sa.Column('model_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("suggested_action IN ('BUY', 'SELL', 'HOLD', 'NO_ACTION')", name='ck_ai_analyses_action'),
    sa.CheckConstraint("uncertainty IN ('LOW', 'MEDIUM', 'HIGH')", name='ck_ai_analyses_uncertainty'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ai_analyses_created_at', 'ai_analyses', ['created_at'], unique=False)
    op.create_index('ix_ai_analyses_signal_id', 'ai_analyses', ['signal_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ai_analyses_signal_id', table_name='ai_analyses')
    op.drop_index('ix_ai_analyses_created_at', table_name='ai_analyses')
    op.drop_table('ai_analyses')
    # ### end Alembic commands ###
